spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yc_user
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # JWT
jwt:
    header: Authorization
    secret: mySecret
    expiration: 604800
    tokenHead: "Bearer "
server:
  port: 8083

