spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yc_user
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.qq.com
    username: 810437416@qq.com
    password: ioqsajztugjpbbje
    default-encoding: UTF-8
    port: 587







  # JWT
jwt:
    header: Authorization
    secret: mySecret
    expiration: 604800
    tokenHead: "Bearer "
server:
  port: 8083

