spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yc_user?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.qq.com
    username: 810437416@qq.com
    password: ioqsajztugjpbbje
    default-encoding: UTF-8
    port: 587
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true


  # JWT
jwt:
    header: Authorization
    secret: mySecret
    expiration: 604800
    tokenHead: "Bearer "
server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8



filePath: C:/YC/
site: http://47.106.105.117:8083





